name: Say Hello

# This tells the robot to wake up whenever we 'push' (save) new code
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Here is the step name the grader is looking for!
      - name: 22f2000805@ds.study.iitm.ac.in
        run: echo "Hello, world!"
